### ISSUE TITLE
License ambiguity

### ISSUE THREAD

**Issue by AddictArts** [igaro/app#6]
The main site http://app.igaro.com/ lists GPL v2 in the footer and the github source LICENSE is GPL v2. However, the link from the install http://app.igaro.com/install/ shows GPL v3. I am hoping that you are not moving to v 3, weird for js library, and considering an artistic license which is far more typical for js github projects. v2 may be too restrictive unfortunately and v3 is definitely in that category.

**Comment by andrewcharnley** [comment]
Thanks for the heads up (should be v2). I'd consider other options but I'd still want to protect the source from being ripped off and sold for profit. Any suggestion?

**Comment by AddictArts** [comment]
The GPL is probably not the best choice to prevent being ripped off. I’m
not a lawyer, but the general idea is that it is used to keep the code
“free as in speech” and not “free as in beer”. Something often said, so
your project could be sold by someone else, so long as they give access to
the source and you credit. They still make money though is the point.

There may be no open source license that can prevent your concern. I also
believe that at least in my personal case the GPL v2 on a JavaScript
project killed it in a big way. The details are not important unless you
really really care, but the project I lead was called Kuda and it was out
on Google Code, which soon will be gone. I wish we could have started with
BSD or MIT, much more common and accepted by open source users. I believe
it would have made a difference and know that in many cases it would have.
We had numerous potential contributors steer clear, because of the GPL v2.

So, I can’t promise you someone will not abuse the license for your
project. Please look at projects like Three.js which is MIT and very
popular and as far as I know it has been successful and not ripped off. If
you still want protection then consider the jQuery dual license, MIT and
GPL. I don’t think it is needed personally, but it is a much better option
than the single GPL v2 license.

Thanks for asking.

**Comment by andrewcharnley** [comment]
Thanks for the advice. It's now MIT.

Regards, Andrew
